export type Hexagram = {
  symbol: string;
  name: string;
  description: string;
};

export const HEXAGRAMS: Hexagram[] = [
  { symbol: '䷀', name: 'Heaven', description: 'Pure creative force, strength through persistence' },
  { symbol: '䷁', name: 'Earth', description: 'Receptive yielding, nourish what is given' },
  { symbol: '䷂', name: 'Sprouting', description: 'Difficult beginning, chaos before order forms' },
  { symbol: '䷃', name: 'Youthful Folly', description: 'Embrace inexperience, seek a worthy teacher' },
  { symbol: '䷄', name: 'Waiting', description: 'Patience before action, nourishment comes' },
  { symbol: '䷅', name: 'Conflict', description: 'Caution needed, do not press forward now' },
  { symbol: '䷆', name: 'Army', description: 'Discipline and order lead to victory' },
  { symbol: '䷇', name: 'Holding Together', description: 'Union through sincerity, seek common ground' },
  { symbol: '䷈', name: 'Small Taming', description: 'Gentle restraint, small gains accumulate slowly' },
  { symbol: '䷉', name: 'Treading', description: 'Walk carefully, conduct yourself with respect' },
  { symbol: '䷊', name: 'Peace', description: 'Heaven and earth unite, prosperity flows freely' },
  { symbol: '䷋', name: 'Standstill', description: 'Stagnation, withdraw and conserve your energy' },
  { symbol: '䷌', name: 'Fellowship', description: 'Open alliance with others, unity of purpose' },
  { symbol: '䷍', name: 'Great Possession', description: 'Abundance earned, share it with humility' },
  { symbol: '䷎', name: 'Modesty', description: 'Quiet virtue, the humble mountain endures' },
  { symbol: '䷏', name: 'Enthusiasm', description: 'Aligned energy, move decisively with the moment' },
  { symbol: '䷐', name: 'Following', description: 'Adapt to the time, yield to what is right' },
  { symbol: '䷑', name: 'Decay', description: 'Work to repair what has been neglected' },
  { symbol: '䷒', name: 'Approach', description: 'The right moment draws near, act with care' },
  { symbol: '䷓', name: 'Contemplation', description: 'Observe deeply before you move' },
  { symbol: '䷔', name: 'Biting Through', description: 'Persist through obstacles, justice prevails' },
  { symbol: '䷕', name: 'Grace', description: 'Beauty in simplicity, adorn without excess' },
  { symbol: '䷖', name: 'Splitting Apart', description: 'Decline is natural, do not force it' },
  { symbol: '䷗', name: 'Return', description: 'The turning point arrives, light returns' },
  { symbol: '䷘', name: 'Innocence', description: 'Act from pure instinct, do not contrive' },
  { symbol: '䷙', name: 'Great Taming', description: 'Accumulate slowly, great potential held in reserve' },
  { symbol: '䷚', name: 'Nourishment', description: 'Tend to what nourishes body and spirit' },
  { symbol: '䷛', name: 'Great Exceeding', description: 'The ridgepole bends, act before it breaks' },
  { symbol: '䷜', name: 'Water', description: 'Flow through danger, remain centered and fluid' },
  { symbol: '䷝', name: 'Fire', description: 'Clarity and light, cling to what sustains you' },
  { symbol: '䷞', name: 'Influence', description: 'Mutual attraction, open yourself to others' },
  { symbol: '䷟', name: 'Duration', description: 'Steadfast endurance, the long path rewards' },
  { symbol: '䷠', name: 'Retreat', description: 'Withdraw wisely, strength is found in stillness' },
  { symbol: '䷡', name: 'Great Power', description: 'Force must be directed, not blindly unleashed' },
  { symbol: '䷢', name: 'Progress', description: 'Steady advance into the light' },
  { symbol: '䷣', name: 'Darkening', description: 'Conceal your light, endure the difficult time' },
  { symbol: '䷤', name: 'Family', description: 'Order within restores order without' },
  { symbol: '䷥', name: 'Opposition', description: 'Tension and contrast, seek the hidden unity' },
  { symbol: '䷦', name: 'Obstruction', description: 'Pause, seek help, do not force the path' },
  { symbol: '䷧', name: 'Deliverance', description: 'Release what binds you, forgive and move on' },
  { symbol: '䷨', name: 'Decrease', description: 'Give what is needed, less becomes more' },
  { symbol: '䷩', name: 'Increase', description: 'Expansion benefits all, act generously now' },
  { symbol: '䷪', name: 'Breakthrough', description: 'Speak truth clearly, expose what is hidden' },
  { symbol: '䷫', name: 'Coming to Meet', description: 'Unexpected encounter, remain discerning' },
  { symbol: '䷬', name: 'Gathering', description: 'Consolidate resources, come together with purpose' },
  { symbol: '䷭', name: 'Rising', description: 'Gradual ascent through quiet persistent effort' },
  { symbol: '䷮', name: 'Exhaustion', description: 'Resources low, maintain integrity in hardship' },
  { symbol: '䷯', name: 'The Well', description: 'Constant source endures, draw from the depths' },
  { symbol: '䷰', name: 'Revolution', description: 'Change is necessary, timing is everything' },
  { symbol: '䷱', name: 'The Cauldron', description: 'Transform raw material into something refined' },
  { symbol: '䷲', name: 'Thunder', description: 'Shock awakens, fear gives way to clarity' },
  { symbol: '䷳', name: 'Mountain', description: 'Keep still, know when not to move' },
  { symbol: '䷴', name: 'Gradual Progress', description: 'Advance step by step, do not rush' },
  { symbol: '䷵', name: 'Marrying Maiden', description: 'Subordinate position, act with awareness' },
  { symbol: '䷶', name: 'Abundance', description: 'Full power at the peak, do not cling' },
  { symbol: '䷷', name: 'Wanderer', description: 'Travel light, conduct yourself with care' },
  { symbol: '䷸', name: 'Wind', description: 'Gentle penetration, consistent effort prevails' },
  { symbol: '䷹', name: 'Joy', description: 'Open exchange, sincerity brings real pleasure' },
  { symbol: '䷺', name: 'Dispersion', description: 'Dissolve rigidity, let barriers melt away' },
  { symbol: '䷻', name: 'Limitation', description: 'Accept necessary constraints, find freedom within' },
  { symbol: '䷼', name: 'Inner Truth', description: 'Sincerity reaches even the most closed hearts' },
  { symbol: '䷽', name: 'Small Exceeding', description: 'Small steps only, do not overreach now' },
  { symbol: '䷾', name: 'After Completion', description: 'Order achieved, guard against complacency' },
  { symbol: '䷿', name: 'Before Completion', description: 'Almost there, careful attention at the threshold' },
];
